// XAJ.idl: XAJ 的 IDL 源
//

// 此文件将由 MIDL 工具处理以
// 生成类型库(XAJ.tlb)和封送处理代码。

import "oaidl.idl";
import "ocidl.idl";

[
	object,
	uuid(a817e7a2-43fa-11d0-9e44-00aa00b6770a),
	dual,
	pointer_default(unique)
]
interface IComponentRegistrar : IDispatch
{
	[id(1)]	HRESULT Attach([in] BSTR bstrPath);
	[id(2)]	HRESULT RegisterAll();
	[id(3)]	HRESULT UnregisterAll();
	[id(4)]	HRESULT GetComponents([out] SAFEARRAY(BSTR)* pbstrCLSIDs, [out] SAFEARRAY(BSTR)* pbstrDescriptions);
	[id(5)]	HRESULT RegisterComponent([in] BSTR bstrCLSID);
	[id(6)] HRESULT UnregisterComponent([in] BSTR bstrCLSID);
};

[
	object,
	uuid(ea7ac902-5dc5-4732-b2dc-46f50fd9385b),
	dual,
	nonextensible,
	pointer_default(unique)
]
interface IModel : IDispatch
{
	//============方法接口设置============//
	[id(1)] HRESULT Run([in] CHAR* argv[1]);
};
[
	uuid(94233707-a67e-4579-9cba-8e92fbf8ee01),
	version(1.0),
	custom(a817e7a1-43fa-11d0-9e44-00aa00b6770a,"{fb867d6b-4a32-4e2f-addd-3047d0103833}")
]
library XAJLib
{
	importlib("stdole2.tlb");
	[
		uuid(fb867d6b-4a32-4e2f-addd-3047d0103833)
	]
	coclass CompReg
	{
		[default] interface IComponentRegistrar;
	};
	[
		uuid(e002b0ec-9a5c-44c8-8b96-bb7648d05f25)
	]
	coclass Model
	{
		[default] interface IModel;
	};
};

import "shobjidl.idl";
